// Destination data — images use keys from lib/images.js REGISTRY
import { pic, imgAlt } from './images';
export { pic, imgAlt };

export const REGIONS = [
  { slug: 'europe',      name: { en: 'Europe',                  zh: '欧洲' },             imgKey: 'region-europe' },
  { slug: 'japan-asia',  name: { en: 'Japan & Asia',            zh: '日本与亚洲' },        imgKey: 'region-japan-asia' },
  { slug: 'australia',   name: { en: 'Australia & New Zealand', zh: '澳大利亚与新西兰' },  imgKey: 'region-australia' },
  { slug: 'islands',     name: { en: 'Indian Ocean & Islands',  zh: '印度洋与岛屿' },     imgKey: 'region-islands' },
  { slug: 'africa',      name: { en: 'Africa Safari',           zh: '非洲野生之旅' },     imgKey: 'region-africa' },
  { slug: 'middle-east', name: { en: 'Middle East',             zh: '中东' },             imgKey: 'region-middle-east' },
  { slug: 'polar',       name: { en: 'Polar & Expedition',      zh: '极地与探险' },       imgKey: 'region-polar' },
  { slug: 'americas',    name: { en: 'Americas',                zh: '美洲' },             imgKey: 'region-americas' },
];

export const DESTINATIONS = [
  {
    slug: 'italy', region: 'europe',
    imgKey: 'dest-italy',
    imgNote: 'Replace with editorial Lake Como or Tuscany asset from approved media kit',
    title:  { en: 'Italy',   zh: '意大利' },
    tagline:{ en: 'Lake Como, Tuscany, Amalfi and the cities in between.', zh: '科莫湖、托斯卡纳、阿马尔菲，以及其间的城市。' },
    why:    { en: 'Italy rewards those who slow down. The combination of art, food, landscape and hospitality is unlike anywhere else in the world — but it is best experienced without rushing between too many cities.', zh: '意大利属于懂得放慢脚步的人。艺术、美食、风景与热情款待的融合举世无双——但最好不要在太多城市间仓促穿梭。' },
    bestTime:{ en: 'May to June and September to October offer the best balance of weather, crowds and cost. July and August can be very hot and crowded in the south.', zh: '五月至六月及九月至十月天气、人流与费用最为均衡。七八月南部可能非常炎热拥挤。' },
    pace:   { en: 'For a first trip, we suggest Lake Como and Tuscany over two weeks rather than trying to cover Rome, Florence, Venice and Amalfi in one go. Italy is better absorbed slowly.', zh: '首次前往，我们建议用两周时间游览科莫湖与托斯卡纳，而非一次性囊括罗马、佛罗伦萨、威尼斯与阿马尔菲。意大利值得慢慢感受。' },
    regions:{ en: 'Lake Como · Tuscany · Amalfi Coast · Florence · Venice · Rome · Sicily', zh: '科莫湖 · 托斯卡纳 · 阿马尔菲海岸 · 佛罗伦萨 · 威尼斯 · 罗马 · 西西里' },
    hotels: { en: 'Villa d\'Este, Grand Hotel Tremezzo, Belmond Villa San Michele, Castiglion del Bosco, Il Pellicano', zh: 'Villa d\'Este、Grand Hotel Tremezzo、贝尔蒙德圣米凯莱别墅、Castiglion del Bosco、Il Pellicano' },
    ourThoughts:{ en: 'For families, we often suggest pairing Lake Como with a Tuscan villa rental. For couples, the Amalfi Coast in late September is exceptional. Do not try to do everything in one trip.', zh: '对于家庭出行，我们常建议将科莫湖与托斯卡纳别墅租住相结合。对于夫妻旅行，九月下旬的阿马尔菲海岸格外迷人。不要试图一次游遍一切。' },
  },
  {
    slug: 'france', region: 'europe',
    imgKey: 'dest-france',
    imgNote: 'Paris aerial — refined, not tourist crowd image',
    title:  { en: 'France',  zh: '法国' },
    tagline:{ en: 'Paris, Provence, the Côte d\'Azur and the Bordeaux wine country.', zh: '巴黎、普罗旺斯、蔚蓝海岸与波尔多葡萄酒产区。' },
    why:    { en: 'France has more Michelin-starred restaurants than any other country, more UNESCO World Heritage Sites than almost anywhere, and a landscape that shifts dramatically from alpine to Mediterranean within hours.', zh: '法国拥有全球最多的米其林星级餐厅、几乎最多的世界遗产，以及从阿尔卑斯到地中海几小时内的戏剧性景观变化。' },
    bestTime:{ en: 'June and September are our preferred months. July and August in the south are beautiful but busy. Paris is wonderful almost year-round.', zh: '六月与九月是我们最推荐的月份。七八月份南部景色优美但人潮涌动。巴黎几乎全年都很迷人。' },
    pace:   { en: 'Paris to Provence is a natural pairing. For longer trips, adding Bordeaux or the Loire Valley makes sense. The Côte d\'Azur is better in May or September than in August.', zh: '巴黎与普罗旺斯是天然的组合。行程较长时，加入波尔多或卢瓦尔河谷很有意义。蔚蓝海岸五月或九月比八月更舒适。' },
    regions:{ en: 'Paris · Provence · Côte d\'Azur · Bordeaux · Loire Valley · Normandy', zh: '巴黎 · 普罗旺斯 · 蔚蓝海岸 · 波尔多 · 卢瓦尔河谷 · 诺曼底' },
    hotels: { en: 'Le Bristol, Hôtel Crillon, Château de la Messardière, La Réserve de Beaulieu, Domaine de Fontenille', zh: 'Le Bristol、Hôtel Crillon、Château de la Messardière、La Réserve de Beaulieu' },
    ourThoughts:{ en: 'France is best experienced slowly. Renting a house in Provence for a week, rather than moving hotels every two nights, tends to reveal a side of the country that hotels alone cannot.', zh: '法国最适合慢慢体验。在普罗旺斯租住一周民宅，而非每两晚换一家酒店，往往能感受到酒店体验之外的另一面。' },
  },
  {
    slug: 'switzerland', region: 'europe',
    imgKey: 'dest-switzerland',
    imgNote: 'Swiss Alps reflection lake — NOT Eiffel Tower',
    title:  { en: 'Switzerland', zh: '瑞士' },
    tagline:{ en: 'The Alps, lake hotels and a quieter Europe.', zh: '阿尔卑斯山、湖畔酒店与更宁静的欧洲。' },
    why:    { en: 'Switzerland is one of the most reliably beautiful countries in Europe. The combination of mountain landscapes, pristine lakes, excellent train travel and world-class hotel infrastructure makes it ideal for families, wellness seekers and slow-travel lovers.', zh: '瑞士是欧洲最可靠的美丽国度之一。山地景观、纯净湖泊、出色的铁路交通与世界级酒店基础设施的结合，使其成为理想目的地。' },
    bestTime:{ en: 'Summer (June–August) for hiking and lake swimming. Winter (December–March) for skiing at Verbier, Zermatt or St. Moritz.', zh: '夏季（六至八月）适合徒步与湖泳。冬季（十二至三月）适合在韦尔比耶、采尔马特或圣莫里茨滑雪。' },
    pace:   { en: 'A week based in one or two locations — Zurich or Geneva as a gateway, then the mountains or Lake Geneva — works well.', zh: '以一两个地点为基础度过一周——以苏黎世或日内瓦为起点，再前往山区或日内瓦湖——效果很好。' },
    regions:{ en: 'Zurich · Geneva · Zermatt · Verbier · St. Moritz · Lucerne · Interlaken', zh: '苏黎世 · 日内瓦 · 采尔马特 · 韦尔比耶 · 圣莫里茨 · 琉森 · 因特拉肯' },
    hotels: { en: 'The Chedi Andermatt, Kulm Hotel St. Moritz, Badrutt\'s Palace, Bürgenstock Resort, Lausanne Palace', zh: 'The Chedi Andermatt、Kulm Hotel St. Moritz、Badrutt\'s Palace、Bürgenstock Resort' },
    ourThoughts:{ en: 'Switzerland is often underrated. For families who want natural beauty, great skiing and impeccable logistics without the complexity of multi-country travel, it is difficult to beat.', zh: '瑞士常常被低估。对于希望拥有自然之美、优质滑雪与完善后勤的家庭，这里很难有对手。' },
  },
  {
    slug: 'japan', region: 'japan-asia',
    imgKey: 'dest-japan',
    imgNote: 'Japanese mountain/temple landscape — NOT random anime or crowded tourist image',
    title:  { en: 'Japan',  zh: '日本' },
    tagline:{ en: 'Tokyo, Kyoto, Hakone, Hokkaido — and the routes between them.', zh: '东京、京都、箱根、北海道——以及它们之间的旅途。' },
    why:    { en: 'Japan is unlike anywhere else. The combination of exceptional food, meticulous service, cultural depth and natural variety is singular. It rewards repeat visits — the country reveals different layers depending on season, region and how slowly you travel.', zh: '日本独一无二。卓越的美食、细致的服务、深厚的文化底蕴与多样的自然风光构成了独特的组合。随着季节、地区与旅行节奏的不同，这个国家会呈现出不同的层次。' },
    bestTime:{ en: 'Cherry blossom (late March to mid-April) and autumn foliage (mid-October to mid-November) are the most celebrated seasons. Winter in Hokkaido (January–February) is exceptional for powder skiing and onsen.', zh: '樱花季（三月底至四月中）与红叶季（十月中至十一月中）是最受推崇的季节。北海道冬季（一至二月）以粉雪滑雪与温泉著称。' },
    pace:   { en: 'We do not recommend rushing Japan. For a first visit, we usually suggest Tokyo and Kyoto, each for at least three nights — with one night in Hakone if time allows.', zh: '我们不太建议把日本安排得太赶。尤其是第一次去，东京与京都各住几晚，往往比每天换酒店舒服很多。' },
    regions:{ en: 'Tokyo · Kyoto · Osaka · Hakone · Hokkaido · Nara · Kanazawa · Niseko', zh: '东京 · 京都 · 大阪 · 箱根 · 北海道 · 奈良 · 金泽 · 二世古' },
    hotels: { en: 'Aman Tokyo, The Peninsula Tokyo, Park Hyatt Tokyo, Hoshinoya Kyoto, Zaborin Hokkaido', zh: '安缦东京、半岛东京、柏悦东京、星のや京都、Zaborin北海道' },
    ourThoughts:{ en: 'Japan is one of our favourite destinations. The quality of service, food and hotel design is consistently excellent. For families with older children, it is remarkable. For couples seeking a slow cultural immersion, Kyoto in autumn is extraordinary.', zh: '日本是我们最喜欢的目的地之一。服务、美食与酒店设计质量始终卓越。对于有大孩子的家庭，这里非常出色。秋天的京都，对于寻求慢节奏文化沉浸的夫妻，堪称非凡。' },
  },
  {
    slug: 'thailand', region: 'japan-asia',
    imgKey: 'dest-thailand',
    imgNote: 'Thailand temple / cultural atmosphere',
    title:  { en: 'Thailand', zh: '泰国' },
    tagline:{ en: 'Bangkok, Chiang Mai, Koh Samui — and the quieter islands beyond.', zh: '曼谷、清迈、苏梅岛——以及更宁静的离岛。' },
    why:    { en: 'Thailand has an extraordinary range — from Bangkok\'s energy and design scene to Chiang Mai\'s temples and food culture, and the warm-water islands. The hospitality infrastructure is excellent at the luxury level.', zh: '泰国拥有非凡的多样性——从曼谷的活力，到清迈的寺院与北部饮食文化，再到温水岛屿。奢华层面的接待基础设施非常出色。' },
    bestTime:{ en: 'November to March is the main high season. The islands have different weather patterns; Koh Samui is better January to April, the Andaman coast November to April.', zh: '十一月至三月是主要旺季。各岛天气规律不同；苏梅岛一至四月为佳，安达曼海岸十一月至四月最宜。' },
    pace:   { en: 'Two to three weeks allows Bangkok, a northern or cultural stop, and a beach finale. Bangkok and one island is a satisfying shorter combination.', zh: '两三周足以游览曼谷、一个文化目的地与最后的海滩时光。曼谷加一个岛屿是令人满足的较短组合。' },
    regions:{ en: 'Bangkok · Chiang Mai · Koh Samui · Koh Yao Noi · Phuket', zh: '曼谷 · 清迈 · 苏梅岛 · 攀牙府 · 普吉岛' },
    hotels: { en: 'Capella Bangkok, Mandarin Oriental Bangkok, Rosewood Bangkok, Samujana, Amanpuri Phuket', zh: 'Capella曼谷、文华东方曼谷、瑰丽曼谷、Samujana、安缦普吉' },
    ourThoughts:{ en: 'Thailand is an exceptional value-to-experience destination at the luxury level. The service culture is genuinely warm. For families, it is one of the most logistically straightforward destinations in Asia.', zh: '泰国在奢华层面是性价比极佳的目的地。服务文化真诚温暖。对于家庭出行，这是亚洲后勤最顺畅的目的地之一。' },
  },
  {
    slug: 'australia', region: 'australia',
    imgKey: 'dest-australia',
    imgNote: 'Australian coastal/landscape — NOT Sydney Opera House unless page is about Sydney',
    title:  { en: 'Australia', zh: '澳大利亚' },
    tagline:{ en: 'Melbourne, Sydney, Tasmania, the wine regions and the natural extremes.', zh: '墨尔本、悉尼、塔斯马尼亚、葡萄酒产区与自然极境。' },
    why:    { en: 'Australia\'s breadth is often underestimated. Beyond the famous cities, there is extraordinary natural variety — from Tasmania\'s wilderness lodges to the ancient landscape of Uluru, the reef and the wine regions. We know this country well.', zh: '澳大利亚的广阔常常被低估。在著名城市之外，还有非凡的自然多样性。我们对这个国家十分熟悉。' },
    bestTime:{ en: 'September to November (spring) and March to May (autumn) are generally pleasant across most regions. The Great Barrier Reef is best June to October.', zh: '九至十一月（春季）与三至五月（秋季）全国大部分地区天气宜人。大堡礁六至十月最佳。' },
    pace:   { en: 'Two weeks allows Melbourne or Sydney plus one natural region — Tasmania, the Reef, the Barossa or the Margaret River. Three weeks opens up combination itineraries.', zh: '两周时间可以游览墨尔本或悉尼加上一个自然区域。三周则可以安排组合行程。' },
    regions:{ en: 'Melbourne · Sydney · Tasmania · Uluru · Barossa Valley · Margaret River · Great Barrier Reef', zh: '墨尔本 · 悉尼 · 塔斯马尼亚 · 乌鲁鲁 · 巴罗莎谷 · 玛格丽特河 · 大堡礁' },
    hotels: { en: 'The Langham Melbourne, Park Hyatt Sydney, Saffire Freycinet, Longitude 131, The Louise Barossa', zh: 'The Langham墨尔本、Park Hyatt悉尼、Saffire Freycinet、Longitude 131、The Louise巴罗莎' },
    ourThoughts:{ en: 'Australia is one of the most rewarding destinations we arrange. The food and wine quality is excellent, the hotel infrastructure is strong, and the natural landscapes are genuinely extraordinary. Melbourne, in particular, is one of our favourite cities in the world.', zh: '澳大利亚是我们安排过的最令人回味的目的地之一。美食与葡萄酒品质出色，酒店基础设施完善，自然景观真正令人叹为观止。墨尔本尤其是我们最喜爱的城市之一。' },
  },
  {
    slug: 'maldives', region: 'islands',
    imgKey: 'dest-maldives',
    imgNote: 'Overwater villa dawn — quiet luxury, NOT generic over-saturated lagoon drone',
    title:  { en: 'Maldives', zh: '马尔代夫' },
    tagline:{ en: 'Private islands, overwater villas and the clearest water in the world.', zh: '私人岛屿、水上别墅与世界上最清澈的海水。' },
    why:    { en: 'The Maldives is one of the most logistically seamless luxury destinations in the world. Every island resort is self-contained; the seaplane transfers are an experience in themselves; and the water quality is consistently extraordinary.', zh: '马尔代夫是世界上后勤最顺畅的奢华目的地之一。每个岛屿度假村自成一体；水上飞机转运本身就是一段体验；水质始终非凡。' },
    bestTime:{ en: 'November to April is the main dry season, with calm seas and excellent visibility for diving. The wet season brings lower rates and fewer guests.', zh: '十一月至四月是主要旱季，海面平静，潜水能见度极佳。雨季房价较低，游客较少。' },
    pace:   { en: 'Seven nights on one island is our minimum recommendation. We advise against changing resorts every three nights.', zh: '我们建议在一个岛屿至少住七晚。我们不建议每三晚更换一次度假村。' },
    regions:{ en: 'North Malé Atoll · South Malé Atoll · Baa Atoll · Raa Atoll', zh: '北马累环礁 · 南马累环礁 · 巴环礁 · 拉环礁' },
    hotels: { en: 'Soneva Fushi, Cheval Blanc Randheli, JOALI Maldives, Four Seasons Resort Maldives at Kuda Huraa, Four Seasons Resort Maldives at Landaa Giraavaru, One&Only Reethi Rah, Patina Maldives, The St. Regis Maldives Vommuli', zh: 'Soneva Fushi、雪瓦布兰Randheli、JOALI马尔代夫、四季Kuda Huraa、四季Landaa Giraavaru、One&Only Reethi Rah、Patina马尔代夫' },
    ourThoughts:{ en: 'The Maldives is one of those destinations where spending more on the right property genuinely makes a significant difference to the experience. We spend considerable time helping clients choose the right island.', zh: '马尔代夫是少数几个在正确住宿上多花钱确实能显著提升体验的目的地之一。我们会花相当多的时间帮助客户根据优先需求选择合适的岛屿。' },
  },
  {
    slug: 'kenya', region: 'africa',
    imgKey: 'dest-kenya',
    imgNote: 'Safari vehicle + landscape at golden hour — NOT only close-up animal',
    title:  { en: 'Kenya',  zh: '肯尼亚' },
    tagline:{ en: 'The Masai Mara, private conservancies and one of the great wildlife spectacles on earth.', zh: '马赛马拉、私人保护区与地球上最壮观的野生动物奇景之一。' },
    why:    { en: 'Kenya is our most recommended African safari destination for first-time visitors. The Masai Mara is consistently exceptional, the private conservancies offer uncrowded, intimate wildlife experiences, and the combination with a beach stay is logistically clean.', zh: '肯尼亚是我们向首次非洲之行者最常推荐的目的地。马赛马拉始终卓越，私人保护区提供不拥挤、亲密的野生动物体验。' },
    bestTime:{ en: 'July to October for the Great Migration crossing. January to March for quieter conditions and newborn animals.', zh: '七至十月观看角马大迁徙过河。一至三月游客较少，可观赏新生动物。' },
    pace:   { en: 'A minimum of four nights in the Mara or conservancies. Combining with two to three nights on the Kenyan coast adds variety without overcomplicating logistics.', zh: '在马拉或保护区至少住四晚。加上肯尼亚海岸两三晚，既增添多样性，又不会使后勤过于复杂。' },
    regions:{ en: 'Masai Mara · Mara North Conservancy · Laikipia · Amboseli · Diani Beach', zh: '马赛马拉 · 马拉北部保护区 · 莱基皮亚 · 安博塞利 · 迪亚尼海滩' },
    hotels: { en: 'Angama Mara, Cottar\'s 1920s Camp, Mahali Mzuri, Sanctuary Olonana, Segera Retreat', zh: 'Angama Mara、Cottar\'s 1920年代营、Mahali Mzuri、Sanctuary Olonana、Segera Retreat' },
    ourThoughts:{ en: 'Kenya is exceptional for families with children over eight years old. The private conservancies adjacent to the Mara offer a fundamentally different experience to the main reserve — fewer vehicles, better guiding.', zh: '肯尼亚对于八岁以上孩子的家庭尤为出色。马拉周边私人保护区提供了与主保护区根本不同的体验——更少的车辆、更好的向导。' },
  },
  {
    slug: 'antarctica', region: 'polar',
    imgKey: 'dest-antarctica',
    imgNote: 'Expedition ship + Antarctic ice — NOT aurora borealis placeholder',
    title:  { en: 'Antarctica', zh: '南极洲' },
    tagline:{ en: 'The end of the earth — and one of the most extraordinary journeys we arrange.', zh: '地球的尽头——也是我们安排过的最非凡的旅程之一。' },
    why:    { en: 'Antarctica is not for every traveller — but for those who feel drawn to it, the experience tends to be genuinely life-changing. The scale of the ice, the density of wildlife, the silence and the quality of light create something that photographs cannot fully capture.', zh: '南极洲并非适合所有旅行者——但对于那些心向往之的人，这段体验往往真正改变人生。冰川的规模、野生动物的密集、寂静与光线的质感，创造出照片无法完全捕捉的感受。' },
    bestTime:{ en: 'The Antarctic season runs November to March. November and December offer pristine snow and penguin chicks; January and February allow access further south; March has interesting ice conditions and is less crowded.', zh: '南极探险季为十一月至三月。十一月和十二月有原始的积雪与企鹅幼雏；一月和二月可前往更南的区域；三月冰况独特且游客较少。' },
    pace:   { en: 'Most Antarctica voyages are 10 to 14 days. We recommend the best vessel and operator for your priorities.', zh: '大多数南极航行为10至14天。我们根据您的优先需求推荐最合适的船只和运营商。' },
    regions:{ en: 'Antarctic Peninsula · South Georgia · Falkland Islands · Weddell Sea', zh: '南极半岛 · 南乔治亚岛 · 福克兰群岛 · 威德尔海' },
    hotels: { en: 'Silversea Expeditions, Ponant, Seabourn, Scenic Eclipse, Hurtigruten Expeditions', zh: 'Silversea探险、Ponant、Seabourn、Scenic Eclipse、Hurtigruten探险' },
    ourThoughts:{ en: 'Antarctica is one of those journeys that people do not regret. The planning is complex and the investment is significant — but clients who have done it consistently tell us it was worth every consideration.', zh: '南极洲是那种人们不会后悔的旅程。规划复杂，投入也相当可观——但完成这段旅程的客户一致告诉我们，一切都值得。' },
  },
  {
    slug: 'patagonia', region: 'americas',
    imgKey: 'dest-patagonia',
    imgNote: 'FIXED — Torres del Paine dramatic mountains, replaced broken image',
    title:  { en: 'Patagonia', zh: '巴塔哥尼亚' },
    tagline:{ en: 'Torres del Paine, the Perito Moreno glacier and the empty end of South America.', zh: '托雷斯德尔潘恩、佩里托莫雷诺冰川与南美洲的空旷尽头。' },
    why:    { en: 'Patagonia offers something genuinely rare: extraordinary natural landscapes with very few people in them. The combination of the Chilean and Argentine sides creates a multi-week journey of remarkable variety.', zh: '巴塔哥尼亚提供了真正稀缺的体验：非凡的自然景观，却几乎没有人。智利与阿根廷两侧的结合构成了多周的丰富旅程。' },
    bestTime:{ en: 'October to April is the Patagonian summer. November and March are our preferred months — the most intense summer heat (January) can be uncomfortable for extended hiking.', zh: '十月至四月是巴塔哥尼亚的夏季。十一月与三月是我们最推荐的月份。' },
    pace:   { en: 'A minimum of ten days to do both the Chilean and Argentine sides justice. Two weeks is better. The journey requires flexibility — Patagonian weather can affect flights with little notice.', zh: '至少需要十天才能兼顾智利与阿根廷两侧。两周更为理想。旅途需要灵活性——巴塔哥尼亚的天气可能毫无预警地影响航班。' },
    regions:{ en: 'Torres del Paine · El Calafate · El Chaltén · Tierra del Fuego · Ushuaia', zh: '托雷斯德尔潘恩 · 卡拉法特 · 查尔滕 · 火地岛 · 乌苏怀亚' },
    hotels: { en: 'Explora Patagonia, awasi Patagonia, Las Torres, Eolo, The Singular Patagonia', zh: 'Explora巴塔哥尼亚、awasi巴塔哥尼亚、Las Torres、Eolo、The Singular巴塔哥尼亚' },
    ourThoughts:{ en: 'Patagonia demands a certain kind of traveller — someone willing to accept unpredictable weather and logistical imperfection in exchange for landscapes of almost incomprehensible scale. For the right client, it is one of the most rewarding journeys we can arrange.', zh: '巴塔哥尼亚需要某种特定类型的旅行者——愿意以接受不可预测的天气和后勤不完美，来换取几乎难以想象的壮阔景观。' },
  },
];

export function getDestinationBySlug(slug) {
  return DESTINATIONS.find(d => d.slug === slug) || null;
}
export function getAllDestinationSlugs() {
  return DESTINATIONS.map(d => d.slug);
}
