export const JOURNEYS = [
  {
    slug: 'italy-family-summer',
    imgKey: 'journey-italy-family',
    region: { en: 'Europe', zh: '欧洲' },
    title:  { en: 'Italy Family Summer',          zh: '意大利家庭夏日' },
    subtitle:{ en: 'Lake Como, Florence and the Amalfi Coast', zh: '科莫湖、佛罗伦萨与阿马尔菲海岸' },
    tags: { en: ['Families','Europe','Summer','Villas'], zh: ['家庭','欧洲','夏季','别墅'] },
    overview:{ en: 'Two weeks in Italy during July or August — Lake Como as a base for the first week, then south through Florence to the Amalfi Coast. We design this around the family\'s pace, with the right villa or hotel at each stop, private transfers between destinations and guide access in Florence and Rome.', zh: '七月或八月在意大利度过两周——第一周以科莫湖为基地，然后向南经佛罗伦萨前往阿马尔菲海岸。我们围绕家庭的节奏设计，每个停留点配以合适的别墅或酒店、目的地间的私人专车，以及佛罗伦萨和罗马的私人向导。' },
    whyWorks:{ en: 'Italy in summer rewards those with the right logistics. A villa on Lake Como solves the space problem for families. A private guide in Florence means the Uffizi does not become a crowded ordeal. The Amalfi Coast by boat is entirely different to the Amalfi Coast by road.', zh: '夏季的意大利，后勤到位的人收获最多。科莫湖的别墅解决了家庭的空间问题。佛罗伦萨的私人向导意味着乌菲兹博物馆不会变成拥挤的煎熬。乘船游阿马尔菲海岸与走公路的体验截然不同。' },
    route:   { en: 'Milan (arrival) → Lake Como (4–5 nights) → Florence (2–3 nights) → Amalfi Coast (4–5 nights) → Naples/Rome (departure)', zh: '米兰（抵达）→ 科莫湖（4–5晚）→ 佛罗伦萨（2–3晚）→ 阿马尔菲海岸（4–5晚）→ 那不勒斯/罗马（离开）' },
    pace:    { en: 'Relaxed. We typically recommend not more than three base changes in two weeks for families. Fewer hotels means more time to settle in.', zh: '轻松。我们通常建议家庭两周内换住地点不超过三次。换的地方越少，越有时间安顿下来。' },
    bestFor: { en: 'Families with children aged 7 and above. Couples who enjoy culture, food and landscape. Multi-generational groups with a villa base.', zh: '7岁以上孩子的家庭。喜欢文化、美食与风景的夫妻。以别墅为基地的多代团体。' },
    hotels:  { en: 'Lake Como: Villa d\'Este, Grand Hotel Tremezzo or a private villa. Florence: Portrait Firenze or Belmond Villa San Michele. Amalfi: Caruso Belvedere or Il San Pietro di Positano.', zh: '科莫湖：Villa d\'Este、Grand Hotel Tremezzo或私人别墅。佛罗伦萨：Portrait Firenze或贝尔蒙德圣米凯莱别墅。阿马尔菲：卡鲁索观景酒店或Il San Pietro di Positano。' },
    ourThoughts:{ en: 'The Lake Como to Amalfi combination is one of our most requested European summer itineraries. The key is not rushing the middle section — Florence deserves two full days minimum, and the drive south through Umbria or via Rome adds value. We advise against driving on the Amalfi road with children under 10.', zh: '科莫湖到阿马尔菲的组合是我们被要求最多的欧洲夏季行程之一。关键是不要赶中间路段——佛罗伦萨最少需要两整天，途经翁布里亚或罗马南下会增添价值。我们建议不要带10岁以下的孩子在阿马尔菲公路上自驾。' },
    customise:{ en: 'Start Your Italy Journey', zh: '开始规划意大利行程' },
  },
  {
    slug: 'japan-winter-family',
    imgKey: 'journey-japan-winter',
    region: { en: 'Japan', zh: '日本' },
    title:  { en: 'Japan Winter Journey',       zh: '日本冬日行旅' },
    subtitle:{ en: 'Tokyo, Hakone and Kyoto in winter', zh: '冬日东京、箱根与京都' },
    tags: { en: ['Japan','Families','Winter','Ryokan'], zh: ['日本','家庭','冬季','旅馆'] },
    overview:{ en: 'Japan in January or February — colder, less crowded and extraordinary in its own way. Tokyo for culture and food, Hakone for a mountain onsen night, Kyoto for temples in the snow. Ten to twelve days works well for families visiting for the first time.', zh: '一月或二月的日本——更凉，游客更少，以其特有的方式令人叹为观止。东京文化与美食，箱根山中温泉一夜，雪中京都寺院。10至12天对于首次造访的家庭来说效果很好。' },
    whyWorks:{ en: 'Winter Japan is genuinely beautiful — the temples in light snow, the onsen experience, the quality of seasonal food. Crowds are manageable. The Shinkansen is reliable. And for families with children who have never visited Japan, the combination of novelty, food quality and logistical ease makes it one of our most recommended first-time destinations.', zh: '冬日日本真正美丽——薄雪中的寺院、温泉体验、时令食材的质量。游客数量可控。新干线准时可靠。对于从未造访日本的孩子的家庭，新奇感、美食质量与后勤便利的结合使其成为我们最推荐的首次目的地之一。' },
    route:   { en: 'Tokyo (3–4 nights) → Hakone by bullet train (1 night at ryokan) → Kyoto (3 nights) → optional: Osaka 1 night + Kansai departure', zh: '东京（3–4晚）→ 乘新干线至箱根（旅馆1晚）→ 京都（3晚）→ 可选：大阪1晚 + 关西离境' },
    pace:    { en: 'Moderate. The Shinkansen connections are easy for families. We recommend keeping bags to a minimum — luggage can be forwarded between hotels using takuhaibin delivery services.', zh: '适中。新干线连接对家庭来说很方便。我们建议尽量减少行李——行李可以通过宅急便服务在酒店之间转运。' },
    bestFor: { en: 'Families with children aged 6 and above. Couples seeking a winter cultural journey. First-time Japan visitors.', zh: '6岁以上孩子的家庭。寻求冬日文化旅程的夫妻。首次造访日本的旅行者。' },
    hotels:  { en: 'Tokyo: Aman Tokyo, The Peninsula Tokyo or Park Hyatt. Hakone: Gora Kadan or Hakone Retreat fore*ste. Kyoto: Hoshinoya Kyoto, The Ritz-Carlton Kyoto or Tawaraya Ryokan.', zh: '东京：安缦东京、半岛东京或柏悦。箱根：強羅花壇或Hakone Retreat fore*ste。京都：星のや京都、丽思卡尔顿京都或俵屋旅馆。' },
    ourThoughts:{ en: 'Kyoto is not a city we recommend rushing. Three nights gives a different rhythm to one night. We always suggest at least one private guide day in Kyoto — the temples and districts make far more sense with context. The onsen night in Hakone is, in our experience, one of those genuinely memorable details that clients still mention years later.', zh: '我们不太建议在京都赶行程。三晚给人不同的节奏感。我们总是建议在京都至少安排一天私人向导——有了背景知识，寺庙和街区会有意义得多。箱根的温泉一夜，以我们的经验来看，是那种客户多年后仍会提起的真正难忘的细节之一。' },
    customise:{ en: 'Start Your Japan Journey', zh: '开始规划日本行程' },
  },
  {
    slug: 'maldives-island-escape',
    imgKey: 'journey-maldives',
    region: { en: 'Indian Ocean', zh: '印度洋' },
    title:  { en: 'Maldives Island Escape',     zh: '马尔代夫岛屿私游' },
    subtitle:{ en: 'Overwater villas, reef and complete seclusion', zh: '水上别墅、礁石与完全的独处' },
    tags: { en: ['Maldives','Honeymoon','Islands','Couples'], zh: ['马尔代夫','蜜月','岛屿','情侣'] },
    overview:{ en: 'Seven to ten nights on a carefully chosen Maldives island — overwater villa, house reef, excellent food and complete disconnection. The key is choosing the right property for your priorities: wildlife, seclusion, dining quality, the presence or absence of children.', zh: '在精心挑选的马尔代夫岛屿上住七至十晚——水上别墅、珊瑚礁、出色的餐饮与完全的断联。关键是根据您的优先需求选择合适的住宿：野生动物、私密性、餐饮质量、是否有孩子。' },
    whyWorks:{ en: 'The Maldives has fewer logistics than almost any comparable destination — a seaplane transfer and you are there. The quality of the water, the wildlife and the hotel design consistently delivers. The challenge is purely in property selection.', zh: '与同类目的地相比，马尔代夫的后勤几乎是最简单的——水上飞机转运，您就到了。水质、野生动物与酒店设计的品质始终令人满意。挑战纯粹在于住宿的选择。' },
    route:   { en: 'Malé (arrival by air) → Seaplane to island → 7–10 nights → Seaplane back to Malé → departure', zh: '马累（飞机抵达）→ 水上飞机至岛屿 → 7–10晚 → 水上飞机返回马累 → 离境' },
    pace:    { en: 'Entirely at your own pace. No programme unless you want one. The best Maldives experience is one with no fixed schedule.', zh: '完全按您自己的节奏。没有固定项目，除非您想要。最好的马尔代夫体验是没有固定日程的体验。' },
    bestFor: { en: 'Honeymoon couples. Families with young children. Those recovering from demanding periods who want complete rest.', zh: '蜜月夫妻。有幼龄孩子的家庭。正在从繁重时期中恢复、需要完全休息的人。' },
    hotels:  { en: 'Soneva Fushi, Cheval Blanc Randheli, JOALI Maldives, Four Seasons Resort Maldives at Kuda Huraa, Four Seasons Resort Maldives at Landaa Giraavaru, Patina Maldives, One&Only Reethi Rah — depending on priorities.', zh: 'Soneva Fushi、雪瓦布兰Randheli、JOALI马尔代夫、四季Kuda Huraa、四季Landaa Giraavaru、Patina马尔代夫——取决于优先需求。' },
    ourThoughts:{ en: 'The Maldives is one of those destinations where spending 20–30% more on the right property makes a significant difference to the experience. We help clients understand which properties are genuinely worth the premium and which are trading on reputation more than current quality.', zh: '马尔代夫是那种在合适住宿上多花20–30%能显著提升体验的目的地之一。我们帮助客户了解哪些住宿真正物有所值，哪些更多是在依靠名气而非当前品质。' },
    customise:{ en: 'Start Your Maldives Journey', zh: '开始规划马尔代夫行程' },
  },
  {
    slug: 'africa-safari-beach',
    imgKey: 'journey-africa',
    region: { en: 'Africa', zh: '非洲' },
    title:  { en: 'Africa Safari & Beach',       zh: '非洲野生与海滩' },
    subtitle:{ en: 'Kenya safari, then the Indian Ocean coast', zh: '肯尼亚野游，再赴印度洋海岸' },
    tags: { en: ['Africa','Safari','Beach','Families'], zh: ['非洲','野游','海滩','家庭'] },
    overview:{ en: 'Ten to twelve days — four to five nights in a private Kenyan conservancy followed by four nights on the Kenya coast or in Zanzibar. The safari provides extraordinary wildlife intensity; the beach allows complete decompression. The combination is logistically clean and experientially exceptional.', zh: '10至12天——在肯尼亚私人保护区住四至五晚，然后在肯尼亚海岸或桑给巴尔岛住四晚。野游提供非凡的野生动物体验强度；海滩让人完全放松。这一组合后勤简洁，体验出色。' },
    whyWorks:{ en: 'The contrast between the bush and the ocean is one of the most satisfying combinations we arrange. Three days in a safari camp changes how you see the ocean. And the logistics work — Nairobi to Mombasa or Zanzibar is an easy connection.', zh: '丛林与海洋之间的对比是我们安排的最令人满足的组合之一。在野生营地待三天，会改变您看待海洋的方式。后勤也很顺畅——内罗毕至蒙巴萨或桑给巴尔岛的连接很方便。' },
    route:   { en: 'Nairobi → Mara North Conservancy (4–5 nights) → Nairobi → Mombasa or Zanzibar (3–4 nights) → departure', zh: '内罗毕 → 马拉北部保护区（4–5晚）→ 内罗毕 → 蒙巴萨或桑给巴尔岛（3–4晚）→ 离境' },
    pace:    { en: 'Active in the conservancy (early morning and late afternoon game drives). Completely relaxed on the coast.', zh: '保护区内节奏积极（清晨与傍晚游猎）。海岸上完全放松。' },
    bestFor: { en: 'Families with children over 8. Couples seeking variety. First-time safari travellers who also want beach time.', zh: '8岁以上孩子的家庭。寻求多样性的夫妻。同时希望享受海滩时光的首次野游旅行者。' },
    hotels:  { en: 'Kenya safari: Angama Mara, Cottar\'s 1920s Camp or Mahali Mzuri. Coast: Alfajiri Villas or Mnarani Club (Kilifi). Zanzibar: Matemwe Lodge or The Residence Zanzibar.', zh: '肯尼亚野游：Angama Mara、Cottar\'s 1920年代营或Mahali Mzuri。海岸：Alfajiri Villas或Mnarani Club（基利菲）。桑给巴尔：Matemwe Lodge或桑给巴尔The Residence。' },
    ourThoughts:{ en: 'This is one of our most frequently requested Africa itineraries. The private conservancies adjacent to the Masai Mara offer a fundamentally different experience to the main reserve — fewer vehicles, more flexibility and better guiding. We always recommend at least one night game drive if the conservancy permits it.', zh: '这是我们最常被要求的非洲行程之一。马赛马拉周边的私人保护区提供了与主保护区根本不同的体验——更少的车辆、更多的灵活性与更好的向导服务。如果保护区允许，我们总是建议至少安排一次夜间游猎。' },
    customise:{ en: 'Start Your Africa Journey', zh: '开始规划非洲行程' },
  },
  {
    slug: 'europe-luxury-rail',
    imgKey: 'exp-luxury-rail',
    region: { en: 'Europe', zh: '欧洲' },
    title:  { en: 'Europe by Luxury Rail',      zh: '欧洲豪华列车之旅' },
    subtitle:{ en: 'The Orient-Express, the Alps and the Italian lakes', zh: '东方快车、阿尔卑斯山与意大利湖区' },
    tags: { en: ['Europe','Luxury Rail','Couples','Adventure'], zh: ['欧洲','豪华列车','情侣','探险'] },
    overview:{ en: 'London or Paris to Venice on the Venice Simplon-Orient-Express — one night in a private cabin with dinner and breakfast — then Lake Como or Florence for several nights. The journey to Venice is the experience; the destination frames it.', zh: '乘威尼斯辛普隆东方快车从伦敦或巴黎至威尼斯——在私人车厢中度过一晚，配晚餐与早餐——然后在科莫湖或佛罗伦萨住几晚。前往威尼斯的旅途本身就是体验；目的地只是为其增添框架。' },
    whyWorks:{ en: 'The Orient-Express is one of those experiences that does not disappoint in the way many iconic things do. The dining car, the suite, the passing landscape — it is genuinely atmospheric. Combining it with Lake Como adds several days of quiet beauty after the drama of the journey.', zh: '东方快车是那些不会像许多标志性事物那样令人失望的体验之一。餐车、套房、掠过的风景——它真正具有氛围感。将其与科莫湖结合，在旅程的精彩之后增添了几天宁静之美。' },
    route:   { en: 'London St Pancras → (VSOE overnight train) → Venice (1 night) → Lake Como (3–4 nights) → Milan departure', zh: '伦敦圣潘克拉斯 → （VSOE夜间列车）→ 威尼斯（1晚）→ 科莫湖（3–4晚）→ 米兰离境' },
    pace:    { en: 'The train itself is unhurried by nature. We recommend not over-programming the Lake Como days — the lake rewards those who simply sit with it.', zh: '列车本身节奏从容。我们建议不要过度安排科莫湖的日程——科莫湖属于那些愿意静静坐下感受它的人。' },
    bestFor: { en: 'Couples celebrating milestones. Architecture and design enthusiasts. Those who want to travel with a sense of occasion.', zh: '庆祝里程碑的夫妻。建筑与设计爱好者。希望以仪式感旅行的人。' },
    hotels:  { en: 'Venice: Aman Venice or Cipriani. Lake Como: Villa d\'Este or Grand Hotel Tremezzo.', zh: '威尼斯：安缦威尼斯或奇普里亚尼。科莫湖：Villa d\'Este或Grand Hotel Tremezzo。' },
    ourThoughts:{ en: 'The Orient-Express books out quickly — particularly the private suites. We recommend planning this journey 6 to 9 months in advance. The experience genuinely lives up to its reputation.', zh: '东方快车订位很快就会售罄——特别是私人套房。我们建议提前6至9个月规划这段旅程。这段体验确实名副其实。' },
    customise:{ en: 'Plan Your Rail Journey', zh: '规划您的列车之旅' },
  },
  {
    slug: 'australia-nature-wine',
    imgKey: 'journey-australia',
    region: { en: 'Australia', zh: '澳大利亚' },
    title:  { en: 'Australia: Nature & Wine',   zh: '澳大利亚自然与美酒' },
    subtitle:{ en: 'Melbourne, the Yarra Valley and the Great Ocean Road', zh: '墨尔本、雅拉谷与大洋路' },
    tags: { en: ['Australia','Wine','Nature','Couples'], zh: ['澳大利亚','美酒','自然','情侣'] },
    overview:{ en: 'Ten days centred on Melbourne — with days in the Yarra Valley wine country, the Mornington Peninsula, and a drive along the Great Ocean Road. Melbourne itself is one of the best dining cities in the world. This itinerary is designed for those who want city culture and natural beauty in equal measure.', zh: '以墨尔本为中心的十天——在雅拉谷葡萄酒产区、莫宁顿半岛度过几天，并沿大洋路驾车游览。墨尔本本身是世界上最好的美食城市之一。这份行程为那些想要城市文化与自然之美并重的旅行者而设计。' },
    whyWorks:{ en: 'Melbourne is consistently underestimated. The food scene, coffee culture, art gallery scene and general liveability are exceptional. Pairing it with the Yarra Valley and the Great Ocean Road creates a ten-day itinerary that never feels repetitive.', zh: '墨尔本始终被低估。美食场景、咖啡文化、艺术画廊氛围与整体生活品质都很出色。将其与雅拉谷和大洋路相结合，创造了一份十天行程，丝毫不感到重复。' },
    route:   { en: 'Melbourne (3–4 nights) → Yarra Valley (2 nights) → Mornington Peninsula (1 night) → Great Ocean Road drive → Melbourne departure', zh: '墨尔本（3–4晚）→ 雅拉谷（2晚）→ 莫宁顿半岛（1晚）→ 大洋路驾车 → 墨尔本离境' },
    pace:    { en: 'Relaxed. This itinerary works well for those who want to spend time in each place rather than covering ground.', zh: '轻松。这份行程适合那些希望在每个地方驻留、而非一路赶路的旅行者。' },
    bestFor: { en: 'Wine and food lovers. Couples seeking culture and nature. Those visiting Australia for the first time who want to understand Melbourne first.', zh: '美酒与美食爱好者。寻求文化与自然的夫妻。首次造访澳大利亚、希望先了解墨尔本的旅行者。' },
    hotels:  { en: 'Melbourne: The Langham Melbourne or Jackalope Mornington. Yarra Valley: Stones of the Yarra Valley or Levantine Hill Estate.', zh: '墨尔本：The Langham墨尔本或Jackalope莫宁顿。雅拉谷：Stones of the Yarra Valley或Levantine Hill Estate。' },
    ourThoughts:{ en: 'We designed this itinerary because we know Melbourne from the inside — our team is based there. The wine region day trips from Melbourne are genuinely excellent, and the Great Ocean Road is one of the most dramatic coastal drives in the world.', zh: '我们设计这份行程，因为我们从内部了解墨尔本——我们的团队就在那里。从墨尔本出发的葡萄酒产区一日游确实出色，大洋路是世界上最壮观的海岸公路之一。' },
    customise:{ en: 'Plan Your Australia Journey', zh: '规划您的澳大利亚行程' },
  },
  {
    slug: 'antarctica-expedition',
    imgKey: 'exp-expedition',
    region: { en: 'Polar', zh: '极地' },
    title:  { en: 'Antarctica Expedition',      zh: '南极洲探险之旅' },
    subtitle:{ en: 'The end of the earth, properly explored', zh: '地球的尽头，真正的探索' },
    tags: { en: ['Antarctica','Expedition','Adventure','Couples'], zh: ['南极洲','探险','冒险','情侣'] },
    overview:{ en: 'A 12-day expedition cruise departing from Ushuaia, Argentina — sailing the Drake Passage, exploring the Antarctic Peninsula by Zodiac, and experiencing wildlife encounters with penguins, seals and whales that photographs cannot prepare you for.', zh: '从阿根廷乌苏怀亚出发的12天探险游轮——穿越德雷克海峡，乘坐橡皮艇探索南极半岛，体验与企鹅、海豹和鲸鱼的野生动物邂逅，这是照片无法让您有所准备的体验。' },
    whyWorks:{ en: 'Antarctica is one of those destinations where the experience consistently matches — and often exceeds — expectations. The scale of the ice, the silence, the wildlife density and the quality of light are simply unlike anything else on earth. Clients who have done it rarely regret the decision.', zh: '南极洲是那种体验始终与预期相符——甚至常常超越预期的目的地之一。冰川的规模、寂静、野生动物的密度与光线的质感，都与地球上任何其他地方不同。完成过这段旅程的客户很少后悔这个决定。' },
    route:   { en: 'Buenos Aires (2 nights) → Ushuaia (1 night) → Drake Passage crossing (2 days) → Antarctic Peninsula (5–6 days) → Drake return → Ushuaia', zh: '布宜诺斯艾利斯（2晚）→ 乌苏怀亚（1晚）→ 德雷克海峡穿越（2天）→ 南极半岛（5–6天）→ 返回穿越 → 乌苏怀亚' },
    pace:    { en: 'Expedition-paced — two Zodiac excursions per day when conditions permit. Active but not physically demanding.', zh: '探险节奏——条件允许时每天两次橡皮艇出行。活跃但体力要求不高。' },
    bestFor: { en: 'Those who have wanted to go to Antarctica for years. Photographers. Nature enthusiasts. Couples or individuals seeking a once-in-a-lifetime journey.', zh: '多年来一直想去南极洲的人。摄影师。自然爱好者。寻求终生难忘旅程的夫妻或个人。' },
    hotels:  { en: 'Ship selection: Silversea Expeditions (Silver Endeavour), Ponant (Le Commandant Charcot), Seabourn (Venture/Pursuit) or Scenic Eclipse — depending on date, budget and experience preference.', zh: '船只选择：Silversea探险（Silver Endeavour）、Ponant（Le Commandant Charcot）、Seabourn（Venture/Pursuit）或Scenic Eclipse——取决于日期、预算与体验偏好。' },
    ourThoughts:{ en: 'Book 10 to 12 months ahead for the best cabin selection. November and March are our preferred months — November for pristine snow and newborn wildlife, March for unusual ice conditions and fewer passengers. The Drake Passage crossing takes two days each way and is part of the experience.', zh: '提前10至12个月预订，以获得最佳舱位选择。十一月与三月是我们最推荐的月份——十一月有原始积雪与新生动物，三月有特殊冰况且游客较少。德雷克海峡穿越单程需要两天，这本身就是体验的一部分。' },
    customise:{ en: 'Plan Your Antarctica Journey', zh: '规划您的南极洲行程' },
  },
  {
    slug: 'swiss-wellness-alpine',
    imgKey: 'journey-swiss',
    region: { en: 'Europe', zh: '欧洲' },
    title:  { en: 'Switzerland: Wellness & Alps', zh: '瑞士疗愈与阿尔卑斯' },
    subtitle:{ en: 'Lake Geneva, mountain air and a genuine wellness reset', zh: '日内瓦湖、山间清新空气与真正的身心重置' },
    tags: { en: ['Switzerland','Wellness','Europe','Couples'], zh: ['瑞士','健康','欧洲','情侣'] },
    overview:{ en: 'Ten days in Switzerland — beginning with a wellness programme at Clinique La Prairie in Montreux, then transferring to the mountains for alpine walking, excellent dining and the extraordinary quality of the Swiss landscape in summer or winter.', zh: '瑞士十天——从蒙特勒Clinique La Prairie的健康项目开始，然后转至山区进行高山徒步、享用出色的餐饮，以及在夏季或冬季感受瑞士景观的非凡品质。' },
    whyWorks:{ en: 'Switzerland has some of the best wellness infrastructure in the world — and some of the most beautiful hotel design. The combination of Clinique La Prairie with a mountain stay in Zermatt or St. Moritz creates a journey that addresses both health and aesthetic pleasure simultaneously.', zh: '瑞士拥有世界上最好的健康基础设施之一——以及最美丽的酒店设计。将Clinique La Prairie与采尔马特或圣莫里茨的山区住宿结合，创造了一段同时满足健康与审美愉悦的旅程。' },
    route:   { en: 'Zurich or Geneva arrival → Montreux / Clinique La Prairie (4–7 nights) → Zermatt or St. Moritz (3–4 nights) → departure', zh: '苏黎世或日内瓦抵达 → 蒙特勒 / Clinique La Prairie（4–7晚）→ 采尔马特或圣莫里茨（3–4晚）→ 离境' },
    pace:    { en: 'Medically-paced at CLP; outdoors-paced in the mountains. We recommend not over-scheduling the mountain section.', zh: 'CLP阶段按医疗节奏；山区阶段按户外节奏。我们建议不要过度安排山区部分的行程。' },
    bestFor: { en: 'Those seeking a genuine health reset alongside beautiful travel. Executives recovering from demanding periods. Couples who want wellness integration without a purely clinical experience.', zh: '寻求真正身心重置同时享受美丽旅行的人。从繁重时期中恢复的高管。希望融入健康元素而非纯临床体验的夫妻。' },
    hotels:  { en: 'Clinique La Prairie (all-inclusive wellness programme). Zermatt: The Omnia or Mont Cervin Palace. St. Moritz: Kulm Hotel or Badrutt\'s Palace.', zh: 'Clinique La Prairie（全包健康计划）。采尔马特：The Omnia或Mont Cervin Palace。圣莫里茨：Kulm Hotel或Badrutt\'s Palace。' },
    ourThoughts:{ en: 'Clinique La Prairie needs to be booked well in advance — their signature revitalisation programme books out months ahead. We help clients navigate the programme options and ensure their health history is communicated appropriately before arrival.', zh: 'Clinique La Prairie需要提前很长时间预订——他们的标志性活化计划提前数月就会售罄。我们帮助客户了解项目选项，并确保在抵达前将健康史适当传达。' },
    customise:{ en: 'Plan Your Swiss Journey', zh: '规划您的瑞士行程' },
  },
];

export function getJourneyBySlug(slug) {
  return JOURNEYS.find(j => j.slug === slug) || null;
}
export function getAllJourneySlugs() {
  return JOURNEYS.map(j => j.slug);
}
