export const TRAVEL_STYLES = [
  {
    slug: 'school-holidays',
    imgKey: 'style-school-holidays',
    title: { en: 'School Holidays & Family Escapes', zh: '学校假期与家庭出行' },
    tagline: { en: 'Light, well-timed family travel designed around school calendars.', zh: '以学校日历为节奏、轻松有序的家庭旅行。' },
    why: { en: 'School holidays create real constraints — and real opportunities. The best family trips we design are ones that account for child energy levels, travel distances, age-appropriate experiences and the reality that parents also need to enjoy the journey. We know which destinations work well with children of different ages during different holiday windows.', zh: '学校假期既带来真实的限制，也创造真正的机会。我们设计的最好的家庭旅行，都考虑到了孩子的体力、旅途距离、适龄体验，以及父母同样需要享受旅途的现实。我们了解不同假期窗口内哪些目的地适合不同年龄的孩子。' },
    bestDest: { en: 'Japan (spring and summer), Australia (summer and Easter), Maldives (all year), Italy (summer), Kenya Safari (school summer)', zh: '日本（春假和暑假）、澳大利亚（暑假和复活节）、马尔代夫（全年）、意大利（暑假）、肯尼亚（暑假）' },
    bestSeason: { en: 'Dependent on school calendar — we design around your specific holiday window.', zh: '取决于学校日历——我们会围绕您具体的假期窗口进行设计。' },
    hotels: { en: 'Four Seasons, Rosewood, Six Senses — all with strong kids\' clubs and family programming. Maldives overwater villas for younger children. Safari lodges from age 8+.', zh: '四季、瑰丽、六善——均有出色的儿童俱乐部与家庭项目。马尔代夫水上别墅适合幼龄孩子。野生营地适合8岁以上。' },
    ifItWereUs: { en: 'For Easter, we usually suggest Japan or Italy — both are manageable in two weeks with children and offer memorable experiences without excessive travel. For summer, Kenya and the Maldives together work remarkably well — safari first, then a week on the water.', zh: '复活节，我们通常建议选择日本或意大利——两者都可以在两周内带孩子舒适游览，并提供难忘体验，旅途也不太辛苦。暑假，肯尼亚与马尔代夫的组合效果非常好——先野游，再在水上住一周。' },
  },
  {
    slug: 'family-journeys',
    imgKey: 'style-family',
    title: { en: 'Family Journeys', zh: '家庭旅行' },
    tagline: { en: 'Multi-generational travel, villa holidays and complex family logistics — designed properly.', zh: '多代同行、别墅假期与复杂家庭后勤——认真规划。' },
    why: { en: 'Family travel at the luxury level is more complex than it appears. Matching hotel infrastructure to children\'s ages, managing meal-times across generations, choosing destinations that engage everyone — these are things we think about carefully. The best family journeys we design have a clear rhythm and do not try to do too much.', zh: '奢华级别的家庭旅行比表面上看起来复杂得多。将酒店基础设施与孩子年龄匹配、协调跨代用餐时间、选择让所有人都投入的目的地——这些都是我们认真思考的事情。我们设计的最好的家庭旅程有清晰的节奏，不试图做太多。' },
    bestDest: { en: 'Japan, Italy, Australia, Maldives, Kenya, Switzerland — all work exceptionally well with the right family configuration and timing.', zh: '日本、意大利、澳大利亚、马尔代夫、肯尼亚、瑞士——配合正确的家庭组合与时机，都表现出色。' },
    bestSeason: { en: 'Varies by destination — we match the itinerary to the family\'s specific dates and children\'s ages.', zh: '因目的地而异——我们根据家庭具体日期与孩子年龄匹配行程。' },
    hotels: { en: 'Four Seasons (consistent family infrastructure), Rosewood (strong kids programming), Private Villas (ideal for multi-generational groups of 8+).', zh: '四季（稳定的家庭基础设施）、瑰丽（出色的儿童项目）、私人别墅（适合8人以上的多代团体）。' },
    ifItWereUs: { en: 'For a family of four with children aged 8 and 12, we would suggest Japan in April — cherry blossom timing, manageable flights, exceptional food and a child-safe, clean environment. Ten to twelve days allows Tokyo, a night in Hakone and Kyoto without feeling rushed.', zh: '对于有一对8岁和12岁孩子的四口之家，我们会建议四月去日本——樱花时节、可承受的飞行时间、出色的美食与对孩子友好、干净的环境。10到12天可以游览东京、在箱根住一晚与京都，而不会感到仓促。' },
  },
  {
    slug: 'culture-discovery',
    imgKey: 'style-culture',
    title: { en: 'Culture & Discovery', zh: '文化探索' },
    tagline: { en: 'Europe, Japan, the Middle East — travel with depth and genuine immersion.', zh: '欧洲、日本、中东——有深度、真正沉浸的旅行。' },
    why: { en: 'Cultural travel is not about visiting museums. It is about finding the right introductions — the right guides, the local context, the small restaurants, the private access, the routes that are not in the guidebook. This is where our network of local specialists makes a real difference.', zh: '文化旅行不在于参观博物馆。而在于找到合适的引荐——合适的向导、当地背景、小餐馆、私人进入途径、不在指南中的路线。这正是我们当地专家网络发挥真正作用的地方。' },
    bestDest: { en: 'Italy, France, Japan, Egypt, Turkey, Jordan, Oman, India', zh: '意大利、法国、日本、埃及、土耳其、约旦、阿曼、印度' },
    bestSeason: { en: 'Spring and autumn for Europe and the Middle East. Year-round for Japan with the right seasonal focus.', zh: '欧洲与中东春秋两季最佳。日本全年皆宜，专注合适的季节主题。' },
    hotels: { en: 'Belmond (heritage properties with local connection), Rocco Forte (European city landmark hotels), Rosewood (strong cultural programming).', zh: '贝尔蒙德（与当地连接的遗产住宿）、罗科福特（欧洲城市地标酒店）、瑰丽（出色的文化项目）。' },
    ifItWereUs: { en: 'For Japan cultural immersion, we would spend three nights in Kyoto in a traditional ryokan, with a private guide for the temples and a dedicated sake tasting evening. The goal is depth, not volume.', zh: '日本文化沉浸，我们会在传统旅馆住三晚，配私人向导游览寺院，并安排一个专属清酒品鉴之夜。目标是深度，而非广度。' },
  },
  {
    slug: 'safari-wilderness',
    imgKey: 'style-safari',
    title: { en: 'Safari & Wilderness', zh: '野生地境' },
    tagline: { en: 'Africa\'s private conservancies, the great migration and the silence of the bush.', zh: '非洲私人保护区、角马大迁徙与丛林的寂静。' },
    why: { en: 'A properly arranged safari — in a private conservancy, with the right timing and the right camp — is consistently one of the most powerful travel experiences we can design. The combination of landscape scale, wildlife proximity and the quality of the best camps is difficult to explain in advance. Clients who have done it well usually want to go back.', zh: '一次妥善安排的野生之旅——在私人保护区、配合正确的时机与合适的营地——始终是我们能设计的最震撼的旅行体验之一。景观规模、野生动物的近距离接触与最佳营地的品质，很难提前用语言描述。真正体验过的客户通常都想再去一次。' },
    bestDest: { en: 'Kenya (Masai Mara), Tanzania (Serengeti, Ngorongoro), Botswana (Okavango Delta), South Africa (Kruger private reserves), Rwanda (gorilla trekking)', zh: '肯尼亚（马赛马拉）、坦桑尼亚（塞伦盖蒂、恩戈罗恩戈罗）、博茨瓦纳（奥卡万戈三角洲）、南非（克鲁格私人保护区）、卢旺达（大猩猩追踪）' },
    bestSeason: { en: 'Great Migration in Kenya and Tanzania: July to October. Botswana: June to October. Gorilla trekking Rwanda: year-round (June–September least rainy).', zh: '肯尼亚和坦桑尼亚角马迁徙：七至十月。博茨瓦纳：六至十月。卢旺达大猩猩追踪：全年（六至九月雨水最少）。' },
    hotels: { en: 'Singita, andBeyond, Angama, Great Plains, Wilderness Safaris, Royal Malewane, Bisate Lodge (Rwanda)', zh: 'Singita、andBeyond、Angama、Great Plains、Wilderness Safaris、Royal Malewane、Bisate Lodge（卢旺达）' },
    ifItWereUs: { en: 'For a first safari, we would choose Kenya over Tanzania — the Mara North Conservancy gives the best combination of wildlife density and privacy. We would combine four nights at Angama Mara with three nights on the coast. For wildlife depth, Botswana is extraordinary — but it requires more investment and a more open schedule.', zh: '首次野生之旅，我们会选择肯尼亚而非坦桑尼亚——马拉北部保护区提供最佳的野生动物密度与私密性组合。我们会将Angama Mara四晚与海岸三晚相结合。寻求野生动物深度体验，博茨瓦纳非常出色——但需要更多投入与更弹性的行程。' },
  },
  {
    slug: 'island-escapes',
    imgKey: 'style-islands',
    title: { en: 'Island Escapes', zh: '岛屿度假' },
    tagline: { en: 'The Maldives, Seychelles, Bali and the quieter islands beyond.', zh: '马尔代夫、塞舌尔、巴厘岛与更宁静的离岛。' },
    why: { en: 'Island travel is less about choosing a destination and more about choosing the right property for the right client. The Maldives has extraordinary variety — from family-oriented resorts with excellent kids\' programmes to deeply private couples-only properties. The Seychelles offers a more textured, less constructed experience. Bali combines villa culture with culture and food. We help clients navigate these differences.', zh: '岛屿旅行与其说是选择目的地，不如说是为合适的客户找到合适的住宿。马尔代夫拥有非凡的多样性——从有出色儿童项目的家庭度假村，到极为私密的情侣专属住宿。塞舌尔提供更有质感、更少人工痕迹的体验。巴厘岛将别墅文化与文化和美食相结合。我们帮助客户理解这些差异。' },
    bestDest: { en: 'Maldives, Seychelles, Fiji, Bali, Koh Samui, Sri Lanka, Mauritius, Turks & Caicos', zh: '马尔代夫、塞舌尔、斐济、巴厘岛、苏梅岛、斯里兰卡、毛里求斯、特克斯和凯科斯' },
    bestSeason: { en: 'Maldives: November to April. Seychelles: April to May, October to November. Bali: May to October.', zh: '马尔代夫：十一月至四月。塞舌尔：四至五月、十至十一月。巴厘岛：五至十月。' },
    hotels: { en: 'Soneva Fushi, Cheval Blanc Randheli, Joali, Four Seasons Landaa Giraavaru, Fregate Island (Seychelles), Nihi Sumba, Samujana', zh: 'Soneva Fushi、雪瓦布兰Randheli、Joali、四季Landaa Giraavaru、Fregate岛（塞舌尔）、Nihi Sumba、Samujana' },
    ifItWereUs: { en: 'For a honeymoon in the Maldives, we would choose a property with fewer than 60 villas, a strong overwater option and an excellent house reef. Soneva Fushi and Cheval Blanc Randheli consistently meet all three. For families, Four Seasons Landaa Giraavaru is difficult to beat.', zh: '马尔代夫蜜月，我们会选择不超过60栋别墅、有优质水上选项与出色礁石的住宿。Soneva Fushi与雪瓦布兰Randheli始终三项俱全。家庭出行，四季Landaa Giraavaru很难被超越。' },
  },
  {
    slug: 'celebration-journeys',
    imgKey: 'style-celebration',
    title: { en: 'Celebration Journeys', zh: '庆典旅行' },
    tagline: { en: 'Honeymoons, anniversaries, milestones — travel designed for significant moments.', zh: '蜜月、周年纪念、人生里程碑——为重要时刻而设计的旅行。' },
    why: { en: 'Milestone travel requires a different approach. The logistics must be invisible, the property must understand the occasion, and the small details — the timing, the setup, the pace — matter more than usual. We have significant experience designing celebration journeys that feel genuinely considered rather than generically romantic.', zh: '里程碑式旅行需要不同的方式。后勤必须无感，住宿必须理解场合，而小细节——时机、布置、节奏——比平时更为重要。我们在设计真正用心而非泛泛浪漫的庆典旅行方面积累了丰富经验。' },
    bestDest: { en: 'Maldives (honeymoon), Amalfi Coast (anniversary), Japan (any milestone), Tuscany (celebration villa), Kenya + islands (honeymoon adventure)', zh: '马尔代夫（蜜月）、阿马尔菲海岸（周年纪念）、日本（任何里程碑）、托斯卡纳（庆典别墅）、肯尼亚加岛屿（蜜月探险）' },
    bestSeason: { en: 'Destination-dependent — we plan around the occasion and the optimal season simultaneously.', zh: '取决于目的地——我们同时围绕场合与最佳季节规划。' },
    hotels: { en: 'Aman (privacy-first), Cheval Blanc (design and romance), Singita (safari celebration), Villa rental (group milestones).', zh: '安缦（私密优先）、雪瓦布兰（设计与浪漫）、Singita（野生庆典）、别墅租住（团体里程碑）。' },
    ifItWereUs: { en: 'For a honeymoon, we rarely suggest the obvious. Japan in April with a private ryokan stay, or Kenya and the Seychelles combined, tend to create more lasting memories than a straightforward beach escape — if the couple is open to something different.', zh: '蜜月旅行，我们很少建议显而易见的选择。四月的日本配私人旅馆入住，或肯尼亚与塞舌尔的组合，往往比单纯的海滩度假留下更持久的记忆——如果这对夫妇愿意尝试不同的体验。' },
  },
  {
    slug: 'slow-luxury',
    imgKey: 'style-slow-luxury',
    title: { en: 'Slow Luxury', zh: '慢游奢华' },
    tagline: { en: 'Lake Como, Tuscany, Kyoto, Aman — travel at a pace that allows genuine absorption.', zh: '科莫湖、托斯卡纳、京都、安缦——以真正沉浸的节奏旅行。' },
    why: { en: 'Slow luxury is not about doing less — it is about choosing fewer places and experiencing them properly. Staying in one Tuscan farmhouse for a week rather than three hotels in five cities. Basing yourself in Kyoto for four nights and allowing the city to reveal itself rather than rushing through. This kind of travel is designed around the idea that the best experiences require time.', zh: '慢游奢华不是做更少的事——而是选择更少的地方并真正体验它们。在托斯卡纳某个农庄住一周，而非在五个城市辗转三家酒店。在京都住四晚，让这座城市自然呈现，而非匆匆而过。这种旅行方式建立在一个理念之上：最好的体验需要时间。' },
    bestDest: { en: 'Lake Como, Tuscany, Provence, Kyoto, Aman properties globally, Swiss lakes', zh: '科莫湖、托斯卡纳、普罗旺斯、京都、全球安缦住宿、瑞士湖区' },
    bestSeason: { en: 'June and September for Europe. Spring (March–May) and Autumn (October–November) for Japan.', zh: '欧洲六月与九月最佳。日本春季（三至五月）与秋季（十至十一月）最佳。' },
    hotels: { en: 'Aman globally, Villa d\'Este Lake Como, Borgo Egnazia Puglia, Hoshinoya Kyoto, private villa rental in Tuscany or Provence.', zh: '全球安缦、科莫湖Villa d\'Este、普利亚Borgo Egnazia、星のや京都、托斯卡纳或普罗旺斯私人别墅租住。' },
    ifItWereUs: { en: 'Lake Como in June for ten days — based in one villa or at Villa d\'Este, with day trips by boat and one evening in Milan. No rushing. The lake has a quality of light in early summer that is genuinely difficult to find elsewhere in Europe.', zh: '六月的科莫湖，住十天——以一栋别墅或Villa d\'Este为基地，乘船游览周边，在米兰度过一个傍晚。不赶路。初夏的湖光在欧洲其他地方真的很难找到。' },
  },
  {
    slug: 'wellness-longevity',
    imgKey: 'style-wellness',
    title: { en: 'Wellness & Longevity', zh: '健康与疗愈' },
    tagline: { en: 'Genuine health outcomes — not just a spa weekend.', zh: '真实的健康效果——而非单纯的水疗周末。' },
    why: { en: 'The wellness travel category spans everything from a hotel spa to a medical longevity programme at Clinique La Prairie. We help clients navigate the difference — and find the right programme for their specific goals, whether that is recovery, prevention, nutrition, sleep or a comprehensive health review.', zh: '健康旅行类别涵盖从酒店水疗到Clinique La Prairie医疗长寿计划的一切。我们帮助客户辨别其中的差异——找到适合其具体目标的正确项目，无论是恢复、预防、营养、睡眠还是全面健康评估。' },
    bestDest: { en: 'Clinique La Prairie (Montreux), Lanserhof (Germany/Austria), SHA Wellness (Alicante), Chiva-Som (Thailand), Six Senses globally, COMO Shambhala (Bali)', zh: 'Clinique La Prairie（蒙特勒）、Lanserhof（德国/奥地利）、SHA Wellness（阿利坎特）、Chiva-Som（泰国）、全球六善、COMO Shambhala（巴厘岛）' },
    bestSeason: { en: 'Year-round for most wellness properties — programmes run continuously.', zh: '大多数健康住宿全年运营，项目持续开展。' },
    hotels: { en: 'Clinique La Prairie, Lanserhof, SHA Wellness, Six Senses, COMO Shambhala, Aman Wellness programmes.', zh: 'Clinique La Prairie、Lanserhof、SHA Wellness、六善、COMO Shambhala、安缦健康项目。' },
    ifItWereUs: { en: 'For genuine longevity focus, Clinique La Prairie in Montreux is the reference point — but it requires advance booking and a minimum stay. For those who want wellness integration without clinical intensity, Six Senses Rome or Six Senses Ibiza offer an excellent introduction to the category.', zh: '真正专注于长寿，Clinique La Prairie是参照标准——但需要提前预订并满足最低住宿天数。对于希望融入健康元素但不需要临床强度的客户，罗马六善或伊比萨六善是了解这一类别的绝佳入门选择。' },
  },
];

export function getStyleBySlug(slug) {
  return TRAVEL_STYLES.find(s => s.slug === slug) || null;
}
export function getAllStyleSlugs() {
  return TRAVEL_STYLES.map(s => s.slug);
}
